/**
 * AI Assist tool-help training document.
 *
 * This is the single source of truth for conversational tool help and
 * semantic routing. Entries describe existing verified tools only; the
 * assistant explains and opens those tools, but never reimplements them.
 */

export type AssistAvailability = "free" | "pro" | "mixed";

export interface AssistToolEntry {
  id: string;
  toolId: string;
  displayName: string;
  category: string;
  availability: AssistAvailability;
  proFeatureName?: string;
  aliases: string[];
  examples: string[];
  capabilitySummary: string;
  answer: string;
  upgradeCopy?: string;
  freeModes?: string[];
  destructive?: boolean;
  focusSection?: string;
}

export const ASSIST_KNOWLEDGE_BASE: AssistToolEntry[] = [
  {
    id: "private-ai-assist-search",
    toolId: "pre-discovery",
    displayName: "Private AI assist & search",
    category: "Legal",
    availability: "pro",
    proFeatureName: "Private AI assist & search",
    aliases: ["ai search", "semantic search", "document q&a", "ask this pdf", "search by meaning", "pre-discovery"],
    examples: [
      "find dollar amounts in the document",
      "show passages about payments and damages",
      "ask questions about this PDF",
      "summarize the document",
      "find clauses by meaning, not exact words",
      "money figures and financial amounts",
      "key dates and deadlines",
    ],
    capabilitySummary: "Searches and answers questions using on-device MiniLM embeddings so the document stays in this browser.",
    answer: "Private AI assist & search finds passages by meaning and answers questions about the open PDF using on-device embeddings. It is meant for understanding, review, and discovery triage — not for deterministic edits.",
    upgradeCopy: "Running semantic search or document Q&A is a Pro feature. The model downloads once while online and is cached on this device for future use.",
  },
  {
    id: "redact",
    toolId: "redact",
    displayName: "Redact for production",
    category: "Legal",
    availability: "free",
    aliases: ["redaction", "black out", "burn redactions", "remove sensitive text", "verifiable redaction"],
    examples: ["redact SSNs", "black out phone numbers", "remove confidential names", "redact every email address"],
    capabilitySummary: "Marks and burns redactions into an exported copy with verification.",
    answer: "Redact for production lets you mark sensitive areas, review matches, then export a verified redacted PDF. The original source bytes stay read-only; the final burn happens only during export.",
    destructive: true,
  },
  {
    id: "ai-detect-sensitive",
    toolId: "redact",
    displayName: "AI detect sensitive info",
    category: "Legal",
    availability: "pro",
    proFeatureName: "AI sensitive-data detection",
    aliases: ["detect pii", "scan sensitive information", "find names", "find organizations", "ner detection"],
    examples: ["scan for sensitive info", "detect SSNs and names", "find all PII", "automatically find private data"],
    capabilitySummary: "Uses on-device detection models and patterns to find likely sensitive items before redaction.",
    answer: "AI sensitive-data detection scans the PDF on this device for likely PII such as SSNs, emails, phone numbers, names, organizations, and financial identifiers, then loads findings into Redact for review.",
    upgradeCopy: "Automatic sensitive-data detection is Pro. Manual redaction stays free.",
    destructive: true,
  },
  {
    id: "pattern-bulk-redact",
    toolId: "redact",
    displayName: "Pattern & bulk redaction",
    category: "Legal",
    availability: "pro",
    proFeatureName: "Pattern / bulk redaction",
    aliases: ["find and redact", "bulk redact", "regex redact", "redact every occurrence"],
    examples: ["redact every occurrence of John Smith", "bulk redact this phrase", "use a pattern to redact account numbers"],
    capabilitySummary: "Finds repeated text or patterns and prepares them for verified redaction.",
    answer: "Pattern & bulk redaction finds every occurrence of a word, phrase, or pattern and sends those matches to Redact for review and verified export.",
    upgradeCopy: "Bulk/pattern redaction is Pro. You can still mark redactions manually for free.",
    destructive: true,
  },
  {
    id: "bates",
    toolId: "bates",
    displayName: "Bates stamp",
    category: "Legal",
    availability: "free",
    aliases: ["bates numbering", "production numbers", "discovery labels", "bates labels"],
    examples: ["add Bates numbers", "stamp ABC000123", "number a production set", "add discovery page identifiers"],
    capabilitySummary: "Adds legal production identifiers with prefix, numbering, and placement controls.",
    answer: "Bates stamping adds unique production identifiers such as ABC000123. It is different from ordinary page numbers because it is used to identify produced pages across discovery sets.",
  },
  {
    id: "page-numbers",
    toolId: "doc-settings",
    displayName: "Page Numbers",
    category: "Layout",
    availability: "free",
    aliases: ["ordinary page numbers", "page x of y", "footer page number", "number pages"],
    examples: ["add page numbers", "put page x of y at the bottom", "number pages 1 2 3"],
    capabilitySummary: "Adds reading page numbers, separate from Bates production labels.",
    answer: "Page Numbers adds ordinary reading numbers such as 1, 2, 3 or Page X of Y. Use Bates instead when you need discovery production identifiers.",
    focusSection: "page-numbers",
  },
  {
    id: "watermark",
    toolId: "watermark",
    displayName: "Watermark",
    category: "Edit",
    availability: "free",
    aliases: ["stamp draft", "confidential watermark", "diagonal watermark", "background mark"],
    examples: ["watermark", "add a confidential watermark", "stamp DRAFT diagonally", "put a translucent mark on every page"],
    capabilitySummary: "Places a visible watermark such as CONFIDENTIAL or DRAFT across pages.",
    answer: "Watermark places a visible mark such as CONFIDENTIAL, DRAFT, or a custom label across selected pages. Use Header/Footer for running text at page edges.",
  },
  {
    id: "split",
    toolId: "split",
    displayName: "Split",
    category: "Assemble",
    availability: "mixed",
    proFeatureName: "Smart Document Splitter",
    aliases: ["split pdf", "separate pages", "break apart", "divide document", "smart split"],
    examples: ["split", "split this PDF", "separate every page", "split every 10 pages", "smart split by sections"],
    capabilitySummary: "Breaks a PDF into smaller files; manual split modes are free and smart split is Pro.",
    answer: "Split breaks a PDF into separate outputs. Free modes include splitting by page ranges or every N pages; smart/AI-assisted splitting is a Pro capability inside the Split tool.",
    freeModes: ["Page ranges", "Every N pages", "Manual split points"],
    upgradeCopy: "Smart split is Pro, but the Split panel also includes free manual modes.",
  },
  {
    id: "merge",
    toolId: "merge",
    displayName: "Merge",
    category: "Assemble",
    availability: "free",
    aliases: ["combine pdfs", "join pdfs", "append files", "assemble documents"],
    examples: ["merge PDFs", "combine these files", "join documents into one PDF"],
    capabilitySummary: "Combines multiple PDFs into one output.",
    answer: "Merge combines multiple PDFs into a single document. Use Organize afterward if you need to reorder pages.",
  },
  {
    id: "organize",
    toolId: "organize",
    displayName: "Organize",
    category: "Assemble",
    availability: "free",
    aliases: ["reorder pages", "delete pages", "move pages", "page thumbnails"],
    examples: ["reorder pages", "delete page 3", "move the exhibit to the front"],
    capabilitySummary: "Reorders, deletes, rotates, or manages pages visually.",
    answer: "Organize shows page thumbnails so you can reorder and remove pages before exporting a new copy.",
  },
  {
    id: "ocr",
    toolId: "ocr",
    displayName: "Make Searchable (OCR)",
    category: "Legal",
    availability: "free",
    aliases: ["ocr", "recognize text", "scanned pdf", "make text selectable"],
    examples: ["make this searchable", "run OCR", "recognize text in scanned pages"],
    capabilitySummary: "Adds a text layer to scanned pages on-device.",
    answer: "Make Searchable runs OCR on scanned-looking pages and adds a text layer so the PDF can be searched and edited. It runs locally and does not alter the original source bytes.",
  },
  {
    id: "sanitize",
    toolId: "sanitize",
    displayName: "Sanitize",
    category: "Legal",
    availability: "free",
    aliases: ["scrub metadata", "remove hidden data", "strip document properties", "clean pdf"],
    examples: ["sanitize this document", "remove metadata", "strip hidden layers and comments"],
    capabilitySummary: "Removes metadata, hidden content, comments, and other risky extras before sharing.",
    answer: "Sanitize removes metadata and hidden document data from an exported copy. It is separate from Redact: sanitize cleans file-level hidden data, while redaction removes visible page content.",
    destructive: true,
  },
  {
    id: "privilege-scan",
    toolId: "privilege-scan",
    displayName: "Privilege review",
    category: "Legal",
    availability: "pro",
    proFeatureName: "Privilege review (AI)",
    aliases: ["privilege scan", "attorney client", "work product", "privileged passages"],
    examples: ["scan for privilege", "find attorney-client communications", "flag work product language"],
    capabilitySummary: "Flags possible attorney-client, work-product, and confidentiality indicators for review.",
    answer: "Privilege review flags possible attorney-client, work-product, counsel-name, and confidentiality signals so a reviewer can inspect them before production.",
    upgradeCopy: "Privilege review is a Pro feature because it uses advanced on-device review logic.",
  },
  {
    id: "exhibit-binder",
    toolId: "exhibit-binder",
    displayName: "Exhibit Binder",
    category: "Legal",
    availability: "pro",
    proFeatureName: "Exhibit Binder",
    aliases: ["binder", "trial exhibits", "exhibit set", "exhibit tabs"],
    examples: ["build an exhibit binder", "assemble trial exhibits", "make a binder with tabs and index"],
    capabilitySummary: "Assembles multiple PDFs into a court-ready exhibit binder with tabs and index.",
    answer: "Exhibit Binder assembles multiple PDFs into a single court-ready binder with cover material, exhibit tabs, and an index.",
    upgradeCopy: "Exhibit Binder is a Pro feature.",
  },
  {
    id: "protect",
    toolId: "protect",
    displayName: "Protect",
    category: "Secure",
    availability: "free",
    aliases: ["password protect", "encrypt pdf", "secure pdf", "require password"],
    examples: ["password protect this PDF", "encrypt the file", "require a password to open"],
    capabilitySummary: "Encrypts the exported PDF with a password.",
    answer: "Protect encrypts a PDF with a password so opening it requires the passphrase you set.",
  },
  {
    id: "unlock",
    toolId: "unlock",
    displayName: "Unlock",
    category: "Secure",
    availability: "free",
    aliases: ["remove password", "decrypt pdf", "unlock encrypted file"],
    examples: ["remove the password", "unlock this PDF", "decrypt a file I own"],
    capabilitySummary: "Removes password protection when you have the password/permission.",
    answer: "Unlock removes password protection from a PDF you are allowed to open, creating an unlocked working copy.",
  },
  {
    id: "repair",
    toolId: "repair",
    displayName: "Repair PDF",
    category: "Secure",
    availability: "free",
    aliases: ["fix pdf", "corrupt pdf", "damaged document", "file will not open"],
    examples: ["repair this PDF", "fix a damaged file", "this PDF is corrupted"],
    capabilitySummary: "Attempts to rebuild a damaged PDF into a usable copy.",
    answer: "Repair PDF attempts to recover a damaged or malformed PDF and writes a fresh repaired copy. Your original file is not changed.",
  },
  {
    id: "sign",
    toolId: "sign",
    displayName: "Sign & Fill",
    category: "Edit",
    availability: "free",
    aliases: ["signature", "fill form", "sign pdf", "type into form"],
    examples: ["sign this PDF", "add my signature", "fill in form fields"],
    capabilitySummary: "Adds signatures, initials, and form text.",
    answer: "Sign & Fill lets you place signatures, initials, dates, and typed text onto the PDF before export.",
  },
  {
    id: "comments",
    toolId: "comments",
    displayName: "Comments",
    category: "Edit",
    availability: "free",
    aliases: ["notes", "sticky notes", "annotations", "highlight", "underline"],
    examples: ["show comments", "add a note", "highlight important passages", "underline text"],
    capabilitySummary: "Adds and reviews non-destructive annotations.",
    answer: "Comments and annotation tools let you mark up the PDF with notes, highlights, underlines, and other review marks without removing content.",
    focusSection: "highlight",
  },
  {
    id: "convert",
    toolId: "convert",
    displayName: "Convert",
    category: "Convert",
    availability: "free",
    aliases: ["export as word", "pdf to docx", "pdf/a", "convert file"],
    examples: ["convert to Word", "export as PDF/A", "save as DOCX"],
    capabilitySummary: "Converts the PDF into supported output formats.",
    answer: "Convert exports the document into supported formats such as Word-style output or archival PDF/A when available.",
  },
  {
    id: "document-hash",
    toolId: "document-hash",
    displayName: "Document Hash",
    category: "Legal",
    availability: "free",
    aliases: ["checksum", "sha-256", "file fingerprint", "chain of custody"],
    examples: ["compute SHA-256", "generate a checksum", "fingerprint this PDF"],
    capabilitySummary: "Computes a file hash for verification and chain-of-custody records.",
    answer: "Document Hash computes a SHA-256 fingerprint for the file so you can prove whether a copy has changed.",
  },
];

export function getAssistToolEntry(idOrToolId: string): AssistToolEntry | undefined {
  return ASSIST_KNOWLEDGE_BASE.find((entry) => entry.id === idOrToolId || entry.toolId === idOrToolId);
}
