/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatermarkRouteImport } from './routes/watermark'
import { Route as SplitRouteImport } from './routes/split'
import { Route as SignRouteImport } from './routes/sign'
import { Route as RotateRouteImport } from './routes/rotate'
import { Route as RedactRouteImport } from './routes/redact'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as ExtractRouteImport } from './routes/extract'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const WatermarkRoute = WatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const RotateRoute = RotateRouteImport.update({
  id: '/rotate',
  path: '/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactRoute = RedactRouteImport.update({
  id: '/redact',
  path: '/redact',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractRoute = ExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/extract': typeof ExtractRoute
  '/merge': typeof MergeRoute
  '/pricing': typeof PricingRoute
  '/redact': typeof RedactRoute
  '/rotate': typeof RotateRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/extract': typeof ExtractRoute
  '/merge': typeof MergeRoute
  '/pricing': typeof PricingRoute
  '/redact': typeof RedactRoute
  '/rotate': typeof RotateRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/extract': typeof ExtractRoute
  '/merge': typeof MergeRoute
  '/pricing': typeof PricingRoute
  '/redact': typeof RedactRoute
  '/rotate': typeof RotateRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/extract'
    | '/merge'
    | '/pricing'
    | '/redact'
    | '/rotate'
    | '/sign'
    | '/split'
    | '/watermark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/extract'
    | '/merge'
    | '/pricing'
    | '/redact'
    | '/rotate'
    | '/sign'
    | '/split'
    | '/watermark'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/extract'
    | '/merge'
    | '/pricing'
    | '/redact'
    | '/rotate'
    | '/sign'
    | '/split'
    | '/watermark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ExtractRoute: typeof ExtractRoute
  MergeRoute: typeof MergeRoute
  PricingRoute: typeof PricingRoute
  RedactRoute: typeof RedactRoute
  RotateRoute: typeof RotateRoute
  SignRoute: typeof SignRoute
  SplitRoute: typeof SplitRoute
  WatermarkRoute: typeof WatermarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watermark': {
      id: '/watermark'
      path: '/watermark'
      fullPath: '/watermark'
      preLoaderRoute: typeof WatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate': {
      id: '/rotate'
      path: '/rotate'
      fullPath: '/rotate'
      preLoaderRoute: typeof RotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redact': {
      id: '/redact'
      path: '/redact'
      fullPath: '/redact'
      preLoaderRoute: typeof RedactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract': {
      id: '/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof ExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ExtractRoute: ExtractRoute,
  MergeRoute: MergeRoute,
  PricingRoute: PricingRoute,
  RedactRoute: RedactRoute,
  RotateRoute: RotateRoute,
  SignRoute: SignRoute,
  SplitRoute: SplitRoute,
  WatermarkRoute: WatermarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
