/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedactRouteImport } from './routes/redact'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as ExtractRouteImport } from './routes/extract'
import { Route as IndexRouteImport } from './routes/index'

const RedactRoute = RedactRouteImport.update({
  id: '/redact',
  path: '/redact',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractRoute = ExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extract': typeof ExtractRoute
  '/merge': typeof MergeRoute
  '/redact': typeof RedactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extract': typeof ExtractRoute
  '/merge': typeof MergeRoute
  '/redact': typeof RedactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extract': typeof ExtractRoute
  '/merge': typeof MergeRoute
  '/redact': typeof RedactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/extract' | '/merge' | '/redact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/extract' | '/merge' | '/redact'
  id: '__root__' | '/' | '/extract' | '/merge' | '/redact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtractRoute: typeof ExtractRoute
  MergeRoute: typeof MergeRoute
  RedactRoute: typeof RedactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redact': {
      id: '/redact'
      path: '/redact'
      fullPath: '/redact'
      preLoaderRoute: typeof RedactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract': {
      id: '/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof ExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtractRoute: ExtractRoute,
  MergeRoute: MergeRoute,
  RedactRoute: RedactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
