/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WordToPdfRouteImport } from './routes/word-to-pdf'
import { Route as WatermarkRouteImport } from './routes/watermark'
import { Route as VerifiableRedactionRouteImport } from './routes/verifiable-redaction'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as ToWordRouteImport } from './routes/to-word'
import { Route as ToImagesRouteImport } from './routes/to-images'
import { Route as ToExcelRouteImport } from './routes/to-excel'
import { Route as SplitRouteImport } from './routes/split'
import { Route as SignRouteImport } from './routes/sign'
import { Route as RotateRouteImport } from './routes/rotate'
import { Route as RedactRouteImport } from './routes/redact'
import { Route as ProtectRouteImport } from './routes/protect'
import { Route as PrivilegeScanRouteImport } from './routes/privilege-scan'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PageNumbersRouteImport } from './routes/page-numbers'
import { Route as OrganizeRouteImport } from './routes/organize'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as ImagesToPdfRouteImport } from './routes/images-to-pdf'
import { Route as HeaderFooterRouteImport } from './routes/header-footer'
import { Route as FlattenRouteImport } from './routes/flatten'
import { Route as ExtractRouteImport } from './routes/extract'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BatesRouteImport } from './routes/bates'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WordToPdfRoute = WordToPdfRouteImport.update({
  id: '/word-to-pdf',
  path: '/word-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const WatermarkRoute = WatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiableRedactionRoute = VerifiableRedactionRouteImport.update({
  id: '/verifiable-redaction',
  path: '/verifiable-redaction',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ToWordRoute = ToWordRouteImport.update({
  id: '/to-word',
  path: '/to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const ToImagesRoute = ToImagesRouteImport.update({
  id: '/to-images',
  path: '/to-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ToExcelRoute = ToExcelRouteImport.update({
  id: '/to-excel',
  path: '/to-excel',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const RotateRoute = RotateRouteImport.update({
  id: '/rotate',
  path: '/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactRoute = RedactRouteImport.update({
  id: '/redact',
  path: '/redact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivilegeScanRoute = PrivilegeScanRouteImport.update({
  id: '/privilege-scan',
  path: '/privilege-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PageNumbersRoute = PageNumbersRouteImport.update({
  id: '/page-numbers',
  path: '/page-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizeRoute = OrganizeRouteImport.update({
  id: '/organize',
  path: '/organize',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesToPdfRoute = ImagesToPdfRouteImport.update({
  id: '/images-to-pdf',
  path: '/images-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderFooterRoute = HeaderFooterRouteImport.update({
  id: '/header-footer',
  path: '/header-footer',
  getParentRoute: () => rootRouteImport,
} as any)
const FlattenRoute = FlattenRouteImport.update({
  id: '/flatten',
  path: '/flatten',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractRoute = ExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BatesRoute = BatesRouteImport.update({
  id: '/bates',
  path: '/bates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bates': typeof BatesRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/compress': typeof CompressRoute
  '/editor': typeof EditorRoute
  '/extract': typeof ExtractRoute
  '/flatten': typeof FlattenRoute
  '/header-footer': typeof HeaderFooterRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/merge': typeof MergeRoute
  '/ocr': typeof OcrRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pricing': typeof PricingRoute
  '/privilege-scan': typeof PrivilegeScanRoute
  '/protect': typeof ProtectRoute
  '/redact': typeof RedactRoute
  '/rotate': typeof RotateRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/to-excel': typeof ToExcelRoute
  '/to-images': typeof ToImagesRoute
  '/to-word': typeof ToWordRoute
  '/unlock': typeof UnlockRoute
  '/vault': typeof VaultRoute
  '/verifiable-redaction': typeof VerifiableRedactionRoute
  '/watermark': typeof WatermarkRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bates': typeof BatesRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/compress': typeof CompressRoute
  '/editor': typeof EditorRoute
  '/extract': typeof ExtractRoute
  '/flatten': typeof FlattenRoute
  '/header-footer': typeof HeaderFooterRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/merge': typeof MergeRoute
  '/ocr': typeof OcrRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pricing': typeof PricingRoute
  '/privilege-scan': typeof PrivilegeScanRoute
  '/protect': typeof ProtectRoute
  '/redact': typeof RedactRoute
  '/rotate': typeof RotateRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/to-excel': typeof ToExcelRoute
  '/to-images': typeof ToImagesRoute
  '/to-word': typeof ToWordRoute
  '/unlock': typeof UnlockRoute
  '/vault': typeof VaultRoute
  '/verifiable-redaction': typeof VerifiableRedactionRoute
  '/watermark': typeof WatermarkRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bates': typeof BatesRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/compress': typeof CompressRoute
  '/editor': typeof EditorRoute
  '/extract': typeof ExtractRoute
  '/flatten': typeof FlattenRoute
  '/header-footer': typeof HeaderFooterRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/merge': typeof MergeRoute
  '/ocr': typeof OcrRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pricing': typeof PricingRoute
  '/privilege-scan': typeof PrivilegeScanRoute
  '/protect': typeof ProtectRoute
  '/redact': typeof RedactRoute
  '/rotate': typeof RotateRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/to-excel': typeof ToExcelRoute
  '/to-images': typeof ToImagesRoute
  '/to-word': typeof ToWordRoute
  '/unlock': typeof UnlockRoute
  '/vault': typeof VaultRoute
  '/verifiable-redaction': typeof VerifiableRedactionRoute
  '/watermark': typeof WatermarkRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bates'
    | '/chat'
    | '/compare'
    | '/compress'
    | '/editor'
    | '/extract'
    | '/flatten'
    | '/header-footer'
    | '/images-to-pdf'
    | '/merge'
    | '/ocr'
    | '/organize'
    | '/page-numbers'
    | '/pricing'
    | '/privilege-scan'
    | '/protect'
    | '/redact'
    | '/rotate'
    | '/sign'
    | '/split'
    | '/to-excel'
    | '/to-images'
    | '/to-word'
    | '/unlock'
    | '/vault'
    | '/verifiable-redaction'
    | '/watermark'
    | '/word-to-pdf'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bates'
    | '/chat'
    | '/compare'
    | '/compress'
    | '/editor'
    | '/extract'
    | '/flatten'
    | '/header-footer'
    | '/images-to-pdf'
    | '/merge'
    | '/ocr'
    | '/organize'
    | '/page-numbers'
    | '/pricing'
    | '/privilege-scan'
    | '/protect'
    | '/redact'
    | '/rotate'
    | '/sign'
    | '/split'
    | '/to-excel'
    | '/to-images'
    | '/to-word'
    | '/unlock'
    | '/vault'
    | '/verifiable-redaction'
    | '/watermark'
    | '/word-to-pdf'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/bates'
    | '/chat'
    | '/compare'
    | '/compress'
    | '/editor'
    | '/extract'
    | '/flatten'
    | '/header-footer'
    | '/images-to-pdf'
    | '/merge'
    | '/ocr'
    | '/organize'
    | '/page-numbers'
    | '/pricing'
    | '/privilege-scan'
    | '/protect'
    | '/redact'
    | '/rotate'
    | '/sign'
    | '/split'
    | '/to-excel'
    | '/to-images'
    | '/to-word'
    | '/unlock'
    | '/vault'
    | '/verifiable-redaction'
    | '/watermark'
    | '/word-to-pdf'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatesRoute: typeof BatesRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  CompressRoute: typeof CompressRoute
  EditorRoute: typeof EditorRoute
  ExtractRoute: typeof ExtractRoute
  FlattenRoute: typeof FlattenRoute
  HeaderFooterRoute: typeof HeaderFooterRoute
  ImagesToPdfRoute: typeof ImagesToPdfRoute
  MergeRoute: typeof MergeRoute
  OcrRoute: typeof OcrRoute
  OrganizeRoute: typeof OrganizeRoute
  PageNumbersRoute: typeof PageNumbersRoute
  PricingRoute: typeof PricingRoute
  PrivilegeScanRoute: typeof PrivilegeScanRoute
  ProtectRoute: typeof ProtectRoute
  RedactRoute: typeof RedactRoute
  RotateRoute: typeof RotateRoute
  SignRoute: typeof SignRoute
  SplitRoute: typeof SplitRoute
  ToExcelRoute: typeof ToExcelRoute
  ToImagesRoute: typeof ToImagesRoute
  ToWordRoute: typeof ToWordRoute
  UnlockRoute: typeof UnlockRoute
  VaultRoute: typeof VaultRoute
  VerifiableRedactionRoute: typeof VerifiableRedactionRoute
  WatermarkRoute: typeof WatermarkRoute
  WordToPdfRoute: typeof WordToPdfRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-to-pdf': {
      id: '/word-to-pdf'
      path: '/word-to-pdf'
      fullPath: '/word-to-pdf'
      preLoaderRoute: typeof WordToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watermark': {
      id: '/watermark'
      path: '/watermark'
      fullPath: '/watermark'
      preLoaderRoute: typeof WatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifiable-redaction': {
      id: '/verifiable-redaction'
      path: '/verifiable-redaction'
      fullPath: '/verifiable-redaction'
      preLoaderRoute: typeof VerifiableRedactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/to-word': {
      id: '/to-word'
      path: '/to-word'
      fullPath: '/to-word'
      preLoaderRoute: typeof ToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/to-images': {
      id: '/to-images'
      path: '/to-images'
      fullPath: '/to-images'
      preLoaderRoute: typeof ToImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/to-excel': {
      id: '/to-excel'
      path: '/to-excel'
      fullPath: '/to-excel'
      preLoaderRoute: typeof ToExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate': {
      id: '/rotate'
      path: '/rotate'
      fullPath: '/rotate'
      preLoaderRoute: typeof RotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redact': {
      id: '/redact'
      path: '/redact'
      fullPath: '/redact'
      preLoaderRoute: typeof RedactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect': {
      id: '/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privilege-scan': {
      id: '/privilege-scan'
      path: '/privilege-scan'
      fullPath: '/privilege-scan'
      preLoaderRoute: typeof PrivilegeScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-numbers': {
      id: '/page-numbers'
      path: '/page-numbers'
      fullPath: '/page-numbers'
      preLoaderRoute: typeof PageNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize': {
      id: '/organize'
      path: '/organize'
      fullPath: '/organize'
      preLoaderRoute: typeof OrganizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images-to-pdf': {
      id: '/images-to-pdf'
      path: '/images-to-pdf'
      fullPath: '/images-to-pdf'
      preLoaderRoute: typeof ImagesToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/header-footer': {
      id: '/header-footer'
      path: '/header-footer'
      fullPath: '/header-footer'
      preLoaderRoute: typeof HeaderFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flatten': {
      id: '/flatten'
      path: '/flatten'
      fullPath: '/flatten'
      preLoaderRoute: typeof FlattenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract': {
      id: '/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof ExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bates': {
      id: '/bates'
      path: '/bates'
      fullPath: '/bates'
      preLoaderRoute: typeof BatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatesRoute: BatesRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  CompressRoute: CompressRoute,
  EditorRoute: EditorRoute,
  ExtractRoute: ExtractRoute,
  FlattenRoute: FlattenRoute,
  HeaderFooterRoute: HeaderFooterRoute,
  ImagesToPdfRoute: ImagesToPdfRoute,
  MergeRoute: MergeRoute,
  OcrRoute: OcrRoute,
  OrganizeRoute: OrganizeRoute,
  PageNumbersRoute: PageNumbersRoute,
  PricingRoute: PricingRoute,
  PrivilegeScanRoute: PrivilegeScanRoute,
  ProtectRoute: ProtectRoute,
  RedactRoute: RedactRoute,
  RotateRoute: RotateRoute,
  SignRoute: SignRoute,
  SplitRoute: SplitRoute,
  ToExcelRoute: ToExcelRoute,
  ToImagesRoute: ToImagesRoute,
  ToWordRoute: ToWordRoute,
  UnlockRoute: UnlockRoute,
  VaultRoute: VaultRoute,
  VerifiableRedactionRoute: VerifiableRedactionRoute,
  WatermarkRoute: WatermarkRoute,
  WordToPdfRoute: WordToPdfRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
